# Generated by Django 4.2 on 2023-04-04 15:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\alban\\OneDrive\\Bureau\\projet easy learning'), upload_to=''),
        ),
    ]
