# Generated by Django 4.2 on 2023-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chapter_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', help_text='Write the title of the course', max_length=500)),
                ('description', models.TextField(default='', help_text='Short description of the course', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='chapters',
            field=models.ManyToManyField(help_text='Select chapters that explains this question ', to='catalog.chapter'),
        ),
    ]
