# Generated by Django 4.1.7 on 2023-04-18 23:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='my_boolean',
            field=models.BooleanField(default=False, verbose_name='Question list?'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dell\\PycharmProjects\\M1_project\\metanit\\elearn\\files'), upload_to=''),
        ),
    ]
