# Generated by Django 4.1.7 on 2023-04-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_file_my_boolean_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='my_boolean',
            new_name='qlist',
        ),
        migrations.AddField(
            model_name='file',
            name='material',
            field=models.BooleanField(default=False, verbose_name='Lectures?'),
        ),
    ]
