# Generated by Django 4.1.7 on 2023-04-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_rename_my_boolean_file_qlist_file_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='material',
        ),
        migrations.RemoveField(
            model_name='file',
            name='qlist',
        ),
    ]
