# Generated by Django 4.1.7 on 2023-04-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_remove_file_material_remove_file_qlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='my_switch',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=3),
        ),
    ]
