# Generated by Django 4.1.7 on 2023-04-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_chapter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
    ]
