# Generated by Django 4.1.7 on 2023-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0008_remove_chapter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default='', help_text='Short description of the chapter', max_length=100),
        ),
    ]
