# Generated by Django 4.1.7 on 2023-04-18 22:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Short description of the chapter', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dell\\PycharmProjects\\M1_project\\metanit\\hello\\files'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', help_text='Write a short description', max_length=500)),
                ('question', models.TextField(max_length=500)),
                ('chapters', models.ManyToManyField(help_text='Selelct chapters that explains this question ', to='elearn.chapter')),
            ],
        ),
    ]
