# Generated by Django 4.1.7 on 2023-04-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_file_my_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='my_switch',
        ),
        migrations.AddField(
            model_name='file',
            name='type_switch',
            field=models.CharField(choices=[('q', 'Question list'), ('l', 'Lectures')], default='on', max_length=3, verbose_name='File type'),
        ),
    ]
