# Generated by Django 4.1.7 on 2023-03-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=500)),
                ('answer_points', models.CharField(choices=[(0, 'too bad'), (1, 'bad'), (2, 'not that bad'), (3, 'ok'), (4, 'good'), (5, 'perfect')], default='0', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='question',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
