# Generated by Django 4.1.7 on 2023-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_question_book_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default='', help_text='Write a short description of the question', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_points',
            field=models.CharField(choices=[('0', 'too bad'), ('1', 'bad'), ('2', 'not that bad'), ('3', 'ok'), ('4', 'good'), ('5', 'perfect')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
