# Generated by Django 4.1.7 on 2023-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_question_title_alter_question_answer_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Short description of the chapter', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default='', help_text='Write a short description', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ManyToManyField(help_text='Selelct chapters that explains this question ', to='hello.chapters'),
        ),
    ]
