# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_chapters_alter_question_title_question_chapter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='chapter',
            new_name='chapters',
        ),
    ]
