# Generated by Django 4.2 on 2023-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.TextField(default='', help_text='Write the title of the chapter', max_length=500),
        ),
    ]
